name: CI

on:
  push:
    branches: [ develop, test4 ]
  pull_request:
    branches: [ master, develop, test4 ]

jobs:
  install and cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NPM cache
        uses: actions/cache@v2
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
  check:
    # if: ${{ github.event_name == 'pull_request' }}
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check pull request branch name
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.ref }}
  
  
        
