name: CI

on:
  push:
    branches: [ develop, test4 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  install-and-cache:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NPM cache
        uses: actions/cache@v2
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
            
      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
  check-pull-request:
    if: ${{ github.event_name == 'pull_request' }}
    needs: install-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check branch name
        run: |
          if [[ ! ${{ github.ref }} =~ ^refs\/heads\/(feature|release)\/GP-[0-9]+$ ]]; then
              echo "::error::Invalid branch name"
              exit 1
          fi
      - name: Check branch commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  
        
