name: CI

on:
  push:
    branches: [ develop, test4 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  install-and-cache:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NPM cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
  check-branch-name:
    if: ${{ github.event_name == 'pull_request' }}
    needs: install-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check branch name
        run: |
          if [[ ! ${{ github.head_ref }} =~ ^(feature|release)\/GP-[0-9]+$ ]]; then
              echo "::error::Invalid branch name"
              exit 1
          fi
  check-branch-commit-messages:
    if: ${{ github.event_name == 'pull_request' }}
    needs: install-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Fetch NPM cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.16.1
      - name: Check branch commit messages
        run: |
          echo npx --version
          echo node --version
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  
        
