name: CI

on:
  push:
    branches: [ master, test4 ]
  pull_request:
    branches: [ master, develop ]

jobs:
  install-and-cache:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NPM cache
        uses: actions/cache@v2
        id: npm-cache
        with:
          path: ./node_modules
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: Install NPM Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm install
  check-branch-name:
    if: ${{ github.event_name == 'pull_request' }}
    needs: install-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Check branch name
        run: |
          if [[ ${{ github.base_ref }} == "develop" ]] && [[ ! ${{ github.head_ref }} =~ ^feature\/GP-[0-9]+$ ]]; then
              echo "::error::Error message for dev"
              exit 1
          fi
          if [[ ${{ github.base_ref }} == "master" ]] && [[ ! ${{ github.head_ref }} =~ ^(release|hotfix)\/GP-[0-9]+$ ]]; then
              echo "::error::Error message for master"
              exit 1
          fi
  check-branch-commit-messages:
    if: ${{ github.event_name == 'pull_request' }}
    needs: install-and-cache
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Fetch NPM cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ hashFiles('**/package-lock.json') }}
      - name: Check branch commit messages
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose



